config/routes.rb
Bridgetroll::Application.routes.draw do
  root to: "events#index"

  devise_for :users, controllers: {registrations: "devise_overrides/registrations"}

  resources :users, only: [:index] do
    resource :profile, :only => [:edit, :update, :show]
    resource :meetup_prompt, :only => [:destroy], :controller => 'users/meetup_prompts'
  end
  resources :meetup_users, :only => [:show]

  resources :locations

  resources :events do
    resources :organizers, :only => [:index, :create, :destroy]
    resources :checkiners, :only => [:index, :create, :destroy]
    resources :volunteers, :only => [:index, :update]

    resources :students, :only => [:index], :controller => 'events/students'
    resources :attendees, :only => [:index, :update], :controller => 'events/attendees'
    resources :emails, :only => [:new, :create], :controller => 'events/emails'

    resources :sections, :only => [:create, :update, :destroy] do
      post :arrange, on: :collection
    end

    resources :rsvps, :except => [:index, :new] do
      new do
        get :volunteer
        get :learn
      end
    end

    resources :event_sessions, :only => [:index] do
      resources :checkins, :only => [:index, :create, :destroy]
    end

    member do
      get "organize"
      get "organize_sections"
      get "levels"
      get "diets"
    end
  end

  resources :external_events

  get "/past_events" => "events#past_events"

  get "/about" => "static_pages#about"

  get "/auth/:provider/callback" => "omniauths#callback"

  if Rails.env.development?
    get "/style_guide" => "static_pages#style_guide"
  end
end

app/controllers/organizers_controller.rb
class OrganizersController < ApplicationController
  before_filter :authenticate_user!
  before_filter :validate_organizer!

  def index
    @organizer_rsvps = @event.organizer_rsvps
    @users = User.not_assigned_as_organizer(@event)
  end

  def create
    @user  = User.find(params[:event_organizer][:user_id])
    @event.organizers << @user
    redirect_to event_organizers_path(@event)
  end

  def destroy
    @event_organizer = @event.rsvps.find(params[:id])

    @event_organizer.destroy
    redirect_to event_organizers_path(@event)
  end
end

app/views/organizers/index.html.erb
<%= content_for(:header_text, @event.title) %>
<%= content_for(:header_link, organize_event_path(@event)) %>

<%= render :partial => 'shared/organizer_breadcrumb', locals: {current_page_title: 'Organizer Assignments'} %>

<h3>Potential Organizers</h3>
<%= form_tag(event_organizers_path(@event), :method => :post)  do %>
    <%= select("event_organizer", "user_id", @users.collect {|u| [ u.full_name, u.id ] }, {:include_blank => ''}) %>
    <%= submit_tag "Assign", :class => "btn btn-primary" %>
<% end %>

<h3>Assigned Organizers</h3>
<table class="table">
  <thead>
  <tr>
    <td></td>
    <td>Name</td>
    <td>Email</td>
    <td></td>
  </tr>
  </thead>
  <tbody>
  <% @organizer_rsvps.each do |rsvp|  %>
      <tr>
        <td class="span1"><%= render 'shared/viewed_gravatars', :email => rsvp.user.email %></td>
        <td><%= rsvp.user.full_name %></td>
        <td><%= rsvp.user.email %></td>
        <td>
          <% if rsvp.user_id != current_user.id %>
              <%= button_to 'Remove', event_organizer_path(@event, rsvp), method: :delete,
                                 :form => {:style => "margin-bottom : 0;"}, :class => "btn btn-mini" %>
          <% end %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>