config/routes.rb
Bridgetroll::Application.routes.draw do
  root to: "events#index"

  devise_for :users, controllers: {registrations: "devise_overrides/registrations"}

  resources :users, only: [:index] do
    resource :profile, :only => [:edit, :update, :show]
    resource :meetup_prompt, :only => [:destroy], :controller => 'users/meetup_prompts'
  end
  resources :meetup_users, :only => [:show]

  resources :locations

  resources :events do
    resources :organizers, :only => [:index, :create, :destroy]
    resources :checkiners, :only => [:index, :create, :destroy]
    resources :volunteers, :only => [:index, :update]

    resources :students, :only => [:index], :controller => 'events/students'
    resources :attendees, :only => [:index, :update], :controller => 'events/attendees'
    resources :emails, :only => [:new, :create], :controller => 'events/emails'

    resources :sections, :only => [:create, :update, :destroy] do
      post :arrange, on: :collection
    end

    resources :rsvps, :except => [:index, :new] do
      new do
        get :volunteer
        get :learn
      end
    end

    resources :event_sessions, :only => [:index] do
      resources :checkins, :only => [:index, :create, :destroy]
    end

    member do
      get "organize"
      get "organize_sections"
      get "levels"
      get "diets"
    end
  end

  resources :external_events

  get "/past_events" => "events#past_events"

  get "/about" => "static_pages#about"

  get "/auth/:provider/callback" => "omniauths#callback"

  if Rails.env.development?
    get "/style_guide" => "static_pages#style_guide"
  end
end

app/views/shared/_checkin_event_sessions.html.erb
<h2>Check-ins</h2>

<% @event.event_sessions.each do |session| %>
  <div class='session-attendance'>
    <h3><%= session.name %></h3>

    <div><%= @checkin_counts[:checkin][session.id] %>/<%= @checkin_counts[:rsvp][session.id] %> Checked In</div>
    <%= link_to "Check in for #{session.name}", event_event_session_checkins_path(@event, session), class: 'btn btn-small' %>
  </div>
<% end %>

app/views/shared/_map.html.erb
<%= gmaps({
    "map_options" => { 
      "auto_adjust" => false, 
      "zoom" => 15, 
      "center_latitude" => location.latitude, 
      "center_longitude" => location.longitude 
    },
    "markers" => { 
      "data" => location.to_gmaps4rails 
    }
  })
%>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <a class="app-name" href=<%= events_path %>><%= render 'shared/logo' %></a>
    <% if user_signed_in? %>
      <span class="nav-blurb">Found a bug? Or some unexpected behavior? <a href="https://github.com/railsbridge/bridge_troll/issues" target="_blank">Let us know</a>!</span>
    <% end %>
    <ul class="nav pull-right">
      <%= render :partial => "devise/menu/login_items" %>
    </ul>
  </div>
</div>

app/views/shared/_organizer_action.erb
<%= link_to path, class: "organizer-action #{defined?(style) && style == :inline ? 'organizer-action-inline' : ''}" do %>
  <div class='organizer-action-button'>
    <i class='<%= icon %>'></i>
    <%= text %>
  </div>
<% end %>

app/views/shared/_organizer_breadcrumb.erb
<div class='organizer-breadcrumb'>
  <%= link_to 'Events', events_path %>
  &raquo;
  <%= link_to @event.title, event_path(@event) %> (<%= link_to 'Edit', edit_event_path(@event) %>, <%= link_to 'Organize', organize_event_path(@event) %>)
  <% if defined?(current_page_title) %>
    &raquo;
    <strong><%= current_page_title %></strong>
  <% end %>
</div>

app/views/shared/_profile_gravatars.html.erb
<div id="gravatar">
<%= gravatar_image_tag(@user.email, :alt => 'Gravatar', :gravatar => { :size => 115 }) %>
<br/>
	<% if @user.email == current_user.email %>
		<div id="change_gravatar"><%=link_to 'Change Gravatar', 'https://en.gravatar.com/emails', :target => "_blank" %>
		</div>
	<% end %>
</div>

app/views/shared/_rsvp_actions.html.erb
<div class='rsvp-text'>
  <% if event.volunteer?(current_user) %>
    You are signed up to volunteer for this event!
  <% elsif event.student?(current_user) %>
    You are signed up to attend this event!
  <% elsif event.waitlisted_student?(current_user) %>
    You are on the waitlist for this event!
  <% end %>
</div>
<% if event.student?(current_user) || event.volunteer?(current_user) || event.waitlisted_student?(current_user) %>
  <%= link_to 'Edit RSVP', edit_event_rsvp_path(event, event.rsvp_for_user(current_user)), :class => 'btn' %>
  <%= link_to 'Cancel RSVP', event_rsvp_path(event, event.rsvp_for_user(current_user)), data: {confirm: 'Are you sure you want to cancel your RSVP?'}, method: :delete, class: 'btn' %>
<% end %>
<% if event.no_rsvp?(current_user) %>
  <% if event.allow_student_rsvp? %>
    <%= link_to attend_button_text(event), learn_new_event_rsvp_path(event), :method => :get, :class => 'btn' %>
  <% end %>
  <%= link_to 'Volunteer', volunteer_new_event_rsvp_path(event), :method => :get, :class => 'btn' %>
<% end %>

app/views/shared/_rsvp_actions_unauthenticated.html.erb
<% if event.allow_student_rsvp? %>
  <a href="#sign_in_dialog"
     class="btn"
     data-toggle="modal"
     data-sign-up-return-to="<%= event_path(event) %>"
     data-return-to="<%= if stay_on_event then event_path(event) else learn_new_event_rsvp_path(event) end %>">
    <%= attend_button_text(event) %>
  </a>
<% end %>
<a href="#sign_in_dialog"
   class="btn"
   data-toggle="modal"
   data-sign-up-return-to="<%= event_path(event) %>"
   data-return-to="<%= if stay_on_event then event_path(event) else volunteer_new_event_rsvp_path(event) end %>">
  Volunteer
</a>

app/views/shared/_rsvps.html.erb
<table class="datatable-sorted table table-striped table-bordered table-condensed">
  <thead>
  <tr>
    <th>Title</th>
    <th>Date</th>
    <th>Location</th>
    <th>Role</th>
  </tr>
  </thead>
  <tbody>
  <% rsvps.each do |rsvp| %>
    <% event = rsvp.event %>
    <tr>
      <td>
        <%= link_to event.title, event %>
        <% if event.meetup_student_event_id %>
          <%= link_to "[S]", event.meetup_url(event.meetup_student_event_id), class: 'meetup-link' %>
        <% end %>
        <% if event.meetup_volunteer_event_id %>
          <%= link_to "[V]", event.meetup_url(event.meetup_volunteer_event_id), class: 'meetup-link' %>
        <% end %>
      </td>
      <td><%= formatted_session_date(event.event_sessions.first) %></td>
      <td><%= event.location.name rescue nil %></td>
      <td><%= rsvp.role.title %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/shared/_sign_in.html.erb
<%= form_for(resource, :as => resource_name, :url => session_path(resource_name)) do |f| %>
  <div>
    <%= f.label :email %>
    <%= f.email_field :email %>
  </div>

  <div>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>

  <% if devise_mapping.rememberable? -%>
    <div>
      <%= f.label :remember_me, class: 'checkbox' do %>
          <%= f.check_box :remember_me %> Remember Me
      <% end %>
    </div>
  <% end -%>

  <div><%= f.submit "Sign in", class: 'btn btn-submit' %></div>
<% end %>

app/views/shared/_sign_in_dialog.html.erb
<div id="sign_in_dialog" class="modal hide <% unless Rails.env.test? %>fade<% end %>" tabindex="-1" role="dialog" aria-labelledby="sign_in_dialogLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h1>Sign in</h1>
  </div>
  <div class="modal-body">
    <%= render partial: "shared/sign_in" %>
    <%= render partial: "devise/shared/links" %>
  </div>
  <div class="modal-footer"></div>
</div>

app/views/shared/_troll.html.erb
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 width="223.79px" height="132.761px" viewBox="0 0 223.79 132.761" enable-background="new 0 0 223.79 132.761"
	 xml:space="preserve">
<g id="Layer_1">
	<path fill="#A5E587" d="M43.762,116.133l2.558-32.097c0,0-16.77,4.64-26.502,15.843s-10.77,13.974-10.77,13.974
		s-1.205,0.28-3.183,2.28H43.762z"/>
	<path fill="#A5E587" d="M217.412,116.133c-1.978-2-3.183-2.297-3.183-2.297s-1.037-2.754-10.77-13.957
		s-26.502-15.826-26.502-15.826l2.558,32.08H217.412z"/>
	<g>
		<path fill="#A5E587" d="M163.139,48.654c0,0-2.946-7.154,4.419-9.26c7.367-2.104,11.156,2.105,12.206-3.788
			c1.053-5.894-5.261-19.571-5.261-19.571s36.288,20.656,21.676,49.877c-9.469,18.94-23.991,9.049-23.991,9.049L163.139,48.654z"/>
	</g>
	<g>
		<path fill="#A5E587" d="M60.167,48.654c0,0,2.946-7.154-4.42-9.26C48.382,37.29,44.593,41.5,43.54,35.606
			c-1.052-5.894,5.263-19.571,5.263-19.571S12.515,36.691,27.125,65.912c9.472,18.94,23.991,9.049,23.991,9.049L60.167,48.654z"/>
	</g>
	<g>
		<path fill="#606060" d="M42.944,79.133c-0.001,0-0.001,0-0.002,0c-4.922,0-11.902-1.917-17.217-12.543
			C10.352,35.844,47.91,14.165,48.292,13.947l6.011-3.343l-2.897,6.321c-2.328,5.047-5.768,14.483-5.092,18.271
			c0.206,1.154,0.465,1.409,0.468,1.411s0.152,0.093,0.786,0.093c0.441,0,0.928-0.034,1.462-0.071
			c0.743-0.051,1.587-0.107,2.537-0.107c1.884,0,3.643,0.242,5.377,0.737c2.794,0.798,4.743,2.306,5.795,4.478
			c1.642,3.392,0.36,7.02,0.097,7.691l-9.271,26.953l-0.609,0.1C52.776,76.602,48.534,79.133,42.944,79.133z M44.544,22.065
			c-2.971,2.304-6.607,5.51-9.83,9.448c-8.944,10.936-10.632,22.174-5.016,33.405c3.451,6.903,7.907,10.403,13.245,10.403
			c0,0,0,0,0.001,0c3.141,0,5.794-1.234,6.924-1.853L58.7,47.809c0.254-0.641,0.768-2.664,0.032-4.156
			c-0.486-0.989-1.471-1.684-3.009-2.123c-1.351-0.386-2.672-0.566-4.157-0.566c-0.798,0-1.526,0.051-2.231,0.1
			c-0.619,0.043-1.203,0.083-1.768,0.083c-3.211,0-4.999-1.636-5.625-5.149C41.296,32.379,42.903,26.636,44.544,22.065z"/>
	</g>
	<path fill="#81AA6B" d="M192.31,114.133c-13.812-35-46.941-61.922-80.52-62.514v-0.018c0,0-0.308,0.007-0.5,0.009
		c-0.192-0.002-0.5-0.009-0.5-0.009v0.018c-33.578,0.592-66.708,27.514-80.519,62.514H192.31z"/>
	<g>
		<path fill="#606060" d="M180.948,79.763c-5.591,0-9.832-2.847-10.01-2.968l-0.61-0.414l-9.271-26.953
			c-0.265-0.672-1.547-4.301,0.096-7.691c1.051-2.172,3-3.678,5.793-4.477c1.736-0.496,3.496-0.736,5.379-0.736
			c0.951,0,1.794,0.058,2.538,0.109c0.534,0.037,1.021,0.072,1.461,0.072c0.634,0,0.783-0.086,0.789-0.09
			c0,0,0.26-0.244,0.465-1.398c0.678-3.793-2.763-13.208-5.091-18.252l-2.899-6.283l6.013,3.424
			c0.382,0.217,37.939,22.053,22.564,52.799C192.852,77.531,185.87,79.763,180.948,79.763z M174.022,73.471
			c1.131,0.617,3.779,1.852,6.926,1.852c5.337,0,9.794-3.5,13.244-10.403c5.617-11.231,3.93-22.47-5.015-33.405
			c-3.222-3.938-6.858-7.146-9.829-9.449c1.641,4.571,3.248,10.314,2.601,13.932c-0.626,3.514-2.413,5.149-5.625,5.149
			c-0.563,0-1.147-0.04-1.768-0.083c-0.705-0.049-1.434-0.1-2.231-0.1c-1.485,0-2.807,0.181-4.158,0.566
			c-1.537,0.439-2.521,1.134-3.008,2.123c-0.734,1.492-0.222,3.516,0.037,4.169l0.042,0.11L174.022,73.471z"/>
	</g>
	<path fill="#606060" d="M33.097,114.133c13.577-33,45.152-59.64,78.086-60.227l0.321-0.042l0.487-0.008
		c20.73,0.361,42.113,11.032,58.668,29.177c8.416,9.227,15.027,20.1,19.529,31.1h4.594c-4.732-12-11.89-24.033-21.074-34.1
		c-16.799-18.412-37.918-29.504-59.918-30.561v-0.158l-2.475,0.076l-2.525-0.057v0.141c-34.248,1.725-66.87,29.658-80.506,64.658
		H33.097z"/>
	<path fill="#A5E587" d="M163.197,114.133c7.462-10,11.939-22.075,11.939-34.896c0-28.896-29.347-60.772-63.347-61.09v-0.008
		c0,0-0.411,0.004-0.5,0.004c-0.088,0-0.5-0.004-0.5-0.004v0.008c-35,0.317-63.347,32.193-63.347,61.09
		c0,12.821,4.325,24.896,11.661,34.896H163.197z"/>
	<g>
		<path fill="none" stroke="#000000" stroke-width="4" stroke-miterlimit="10" d="M170.083,88.43"/>
	</g>
	<g>
		<path fill="#606060" d="M39.02,69.988l-1.601-6.931l1.227-0.858c0.022-0.018,3.361-2.461,3.69-6.566
			c0.298-3.723-3.858-6.058-3.9-6.081l-1.72-0.947l1.143-2.88c0.482-1.205,1.664-3.004,1.896-3.352l3.695,2.462
			c-0.349,0.522-0.857,1.345-1.193,1.97c1.963,1.556,4.867,4.653,4.506,9.183c-0.352,4.369-2.846,7.382-4.377,8.843l0.959,4.16
			L39.02,69.988z"/>
	</g>
	<g>
		<path fill="#606060" d="M96.676,93.461c-0.682,0-1.344-0.079-1.973-0.258c-1.794-0.511-3.14-1.736-3.892-3.544
			c-1.577-3.79-1.457-6.893,0.354-9.223c3.734-4.803,13.166-3.579,14.229-3.423l-0.642,4.393l0.321-2.196l-0.318,2.197
			c-2.561-0.369-8.396-0.423-10.086,1.757c-0.756,0.976-0.674,2.587,0.241,4.789c0.287,0.69,0.654,0.879,1.008,0.979
			c2.416,0.687,7.49-2.155,9.565-3.642l2.586,3.609C107.343,89.421,101.546,93.461,96.676,93.461z"/>
	</g>
	<g>
		<path fill="none" stroke="#000000" stroke-width="4" stroke-miterlimit="10" d="M53.808,88.43"/>
	</g>
	<g>
		<path fill="#606060" d="M92.79,67.279c0-4.01-3.51-7.26-7.52-7.26s-7.48,3.25-7.48,7.26c0,1.523,0,1.634,0,3.158
			c0,4.009,3.491,7.26,7.5,7.26c4.011,0,7.5-3.251,7.5-7.26C92.79,68.913,92.79,68.803,92.79,67.279z"/>
	</g>
	<g>
		<path fill="#606060" d="M77.849,13.942c1.878-0.804,11,6.707,13.146,9.657c2.146,2.951-7.779,12.609-12.072,7.244
			C75.064,26.021,75.971,14.748,77.849,13.942z"/>
	</g>
	<g>
		<circle fill="#FFFFFF" cx="85.481" cy="66.438" r="2.48"/>
	</g>
	<g>
		<path fill="#606060" d="M184.874,69.988l-4.327-0.998l0.96-4.16c-1.531-1.461-4.027-4.474-4.376-8.844
			c-0.362-4.529,2.541-7.626,4.505-9.182c-0.336-0.627-0.846-1.447-1.193-1.969l3.695-2.463c0.232,0.348,1.414,2.146,1.896,3.354
			l1.157,2.891l-1.745,0.939c-0.032,0.019-4.188,2.354-3.889,6.076c0.327,4.105,3.666,6.549,3.699,6.573l1.199,0.862l-0.32,1.448
			L184.874,69.988z"/>
	</g>
	<g>
		<path fill="#606060" d="M129.741,93.461c-4.869,0-10.666-4.04-11.393-4.561l2.586-3.609c2.645,1.889,7.361,4.271,9.565,3.641
			c0.354-0.101,0.72-0.289,1.008-0.979c0.916-2.202,0.997-3.813,0.24-4.789c-1.69-2.18-7.526-2.125-10.087-1.757l-0.639-4.394
			c1.062-0.156,10.496-1.379,14.229,3.424c1.812,2.33,1.931,5.432,0.355,9.221c-0.753,1.809-2.099,3.034-3.894,3.545
			C131.087,93.382,130.423,93.461,129.741,93.461z"/>
	</g>
	<g>
		<path fill="#606060" d="M111.893,45.745c-7.44,0-11.646-2.317-11.821-2.415l2.177-3.871c0.021,0.012,3.46,1.846,9.645,1.846
			c6.205,0,9.749-1.846,9.785-1.864l2.12,3.901C123.618,43.44,119.32,45.745,111.893,45.745z"/>
	</g>
	<g>
		<rect x="86.79" y="49.133" fill="#606060" width="50" height="5"/>
	</g>
	<g>
		<path fill="#606060" d="M129.79,67.279c0-4.01,3.984-7.26,7.994-7.26s7.626,3.25,7.626,7.26c0,1.523,0.164,1.634,0.164,3.158
			c0,4.009-3.882,7.26-7.892,7.26c-4.011,0-7.893-3.251-7.893-7.26C129.79,68.913,129.79,68.803,129.79,67.279z"/>
	</g>
	<polygon fill="#FFFFFF" points="138.038,104.314 141.415,95.25 147.54,103.25 142.915,105.75 	"/>
	<polygon fill="#FFFFFF" points="85.54,104.314 82.163,95.25 76.038,103.25 80.663,105.75 	"/>
	<polygon fill="#FFFFFF" points="101.54,106.314 96.54,100.625 92.038,105.25 96.663,107.75 	"/>
	<polygon fill="#FFFFFF" points="132.54,106.314 127.54,100.625 123.038,105.25 127.663,107.75 	"/>
	<g>
		<path fill="#606060" d="M146.044,13.942c-1.879-0.804-11,6.707-13.146,9.657c-2.145,2.951,7.781,12.609,12.072,7.244
			C148.827,26.021,147.921,14.748,146.044,13.942z"/>
	</g>
	<g>
		<path fill="#A5E587" d="M124.326,78.417c2.78,3.238,0.728,8.411-0.687,9.327c-2.931,1.896-5.433,4.158-10.326,4.158
			c-4.893,0-7.605-2.263-10.533-4.158c-1.416-0.916-3.471-6.078-0.689-9.315c2.975-3.464,6.804-4.142,10.855-4.142
			C116.996,74.287,121.351,74.953,124.326,78.417z"/>
		<path fill="#606060" d="M113.313,94.123c-4.976,0-8.022-2.037-10.711-3.834c-0.342-0.229-0.684-0.458-1.029-0.682
			c-1.636-1.057-2.672-3.631-2.973-5.713c-0.383-2.654,0.258-5.109,1.806-6.912c3.741-4.356,8.667-4.915,12.54-4.915
			c3.799,0,9.288,0.509,13.064,4.902c1.549,1.805,2.189,4.263,1.805,6.922c-0.301,2.083-1.336,4.659-2.97,5.716
			c-0.41,0.266-0.812,0.539-1.212,0.811C121.077,92.154,118.182,94.123,113.313,94.123z M112.946,76.508
			c-4.46,0-7.117,0.976-9.172,3.367c-1.744,2.031-0.358,5.474,0.277,6.054c0.298,0.187,0.658,0.427,1.02,0.669
			c2.476,1.655,4.614,3.085,8.242,3.085c3.502,0,5.505-1.36,7.824-2.937c0.428-0.291,0.857-0.582,1.295-0.866
			c0.569-0.532,1.955-3.983,0.209-6.017C120.648,77.543,117.657,76.508,112.946,76.508z"/>
	</g>
	<g>
		<rect x="103.79" y="62.133" fill="#606060" width="17" height="5"/>
	</g>
	<g>
		<circle fill="#FFFFFF" cx="138.412" cy="66.438" r="2.479"/>
	</g>
	<g>
		<path fill="#606060" d="M138.582,107.569l-3.288-1.345c0.014-0.035,1.415-3.461,2.18-5.607c0.234-0.654,0.4-1.496,0.561-2.312
			c0.404-2.054,0.822-4.177,2.736-4.653c2.51-0.634,5.879,2.85,10.031,10.332l-3.105,1.723c-2.014-3.627-4.504-7.098-5.845-8.235
			c-0.124,0.464-0.242,1.063-0.332,1.521c-0.186,0.943-0.378,1.918-0.701,2.82C140.026,104.033,138.64,107.426,138.582,107.569z"/>
	</g>
	<g>
		<path fill="#606060" d="M70.447,95.687c-0.362,0.02-1.282,0.22-1.663,0.708c-0.329,0.421-0.274,1.15-0.17,1.689l0.08,0.413
			l-0.016,0.024c0.404,1.409,4.087,4.835,17.175,5.793c19.264,1.41,32.918,1.41,52.185,0c14.897-1.09,16.959-5.212,17.182-5.826
			l-0.061-0.32l0.119-0.059c0.15-0.783,0.094-1.354-0.172-1.693c-0.414-0.532-1.385-0.7-1.691-0.717l0.167-4.438
			c0.324,0.011,3.224,0.166,4.986,2.375c0.752,0.941,1.542,2.588,1.103,5.128c-0.111,1.942-1.936,8.561-21.309,9.979
			c-9.752,0.714-18.084,1.07-26.416,1.07s-16.664-0.356-26.417-1.07c-19.375-1.418-21.198-8.06-21.309-10.005
			c-0.44-2.541,0.351-4.188,1.104-5.128c1.765-2.204,4.666-2.353,4.991-2.362L70.447,95.687"/>
	</g>
	<g>
		<path fill="#606060" d="M85.312,107.57c-0.059-0.144-1.447-3.537-2.24-5.76c-0.322-0.902-0.514-1.877-0.7-2.82
			c-0.089-0.457-0.208-1.055-0.331-1.518c-1.342,1.137-3.83,4.607-5.844,8.234l-3.106-1.723c4.151-7.483,7.534-10.951,10.034-10.332
			c1.911,0.478,2.328,2.6,2.732,4.65c0.16,0.816,0.327,1.66,0.561,2.314c0.766,2.146,2.168,5.572,2.182,5.605L85.312,107.57z"/>
	</g>
	<g>
		<path fill="#606060" d="M99.252,107.796c-0.707-2.288-1.936-4.731-2.637-5.29c-0.693,0.414-2.006,2.373-2.824,4.255l-3.258-1.417
			c0.891-2.049,3.31-6.778,6.463-6.425c2.919,0.324,4.793,5.046,5.649,7.831L99.252,107.796z"/>
	</g>
	<g>
		<path fill="#606060" d="M124.642,107.795l-3.395-1.045c0.856-2.785,2.73-7.507,5.65-7.831c3.152-0.354,5.569,4.376,6.461,6.425
			l-3.258,1.418c-0.822-1.883-2.133-3.842-2.824-4.256C126.573,103.064,125.345,105.508,124.642,107.795z"/>
	</g>
	<rect x="5.79" y="114.133" fill="#606060" width="212" height="5"/>
	<path fill="#606060" d="M62.427,114.133c-7.756-10-12.41-22.012-12.41-34.896c0-26.934,26.709-58.521,61.146-58.837l0.354-0.021
		l0.494-0.004c34.437,0.314,61.146,31.932,61.146,58.865c0,12.885-4.654,24.893-12.41,34.893h5.316
		c7.318-10,11.304-22.422,11.304-34.896c0-28.391-27.577-61.619-63.577-63.25v-0.084l-2.489,0.02l-2.511-0.012v0.076
		c-36,1.631-63.313,34.859-63.313,63.25c0,12.475,3.938,24.896,11.234,34.896H62.427z"/>
	<path fill="#606060" d="M217.79,114.338c-1.012-0.74-1.793-1.273-2.271-1.589c-0.83-1.479-3.339-5.253-10.794-13.835
		c-10.054-11.574-26.872-16.358-27.582-16.56l-1.193,4.277c0.162,0.046,16.26,4.644,25.424,15.194
		c8.994,10.354,10.348,13.215,10.4,13.331l0.265,0.762l0.276,0.214h5.475V114.338z"/>
	<path fill="#606060" d="M46.134,82.354c-0.71,0.201-17.528,4.985-27.582,16.56c-7.455,8.582-9.964,12.356-10.794,13.835
		c-0.428,0.282-1.104,0.745-1.968,1.369v2.015h5.172l0.276-0.214l0.265-0.729c0.053-0.116,1.406-2.994,10.4-13.348
		c9.164-10.551,25.262-15.157,25.424-15.202L46.134,82.354z"/>
</g>
<g id="Layer_2">
</g>
</svg>

app/views/shared/_viewed_gravatars.html.erb
<%= gravatar_image_tag(email, :alt => 'Gravatar', :gravatar => { :size => 38 }) %>

app/views/shared/_welcome.html.erb
<div class="row-fluid">
  <div class="welcome-box">
    <div class="welcome-content">
      <div class="troll">
        <%= render 'shared/troll_plus_logo' %>
      </div>
      <div class="welcome-message">
        <h2>Do you want to learn to code with fun people? <%= link_to "Sign up", new_user_registration_path %> and RSVP for an event.</h2>
        <h2>Or, learn more <%= link_to "about Bridge Troll",
                                                      about_path %>.</h2>
        <h2>This is open source software, so feel free to <%= link_to "peruse our code.", "http://www.github.com/railsbridge/bridge_troll" %></h2>
      </div>
    </div>
  </div>
</div>