config/routes.rb
Bridgetroll::Application.routes.draw do
  root to: "events#index"

  devise_for :users, controllers: {registrations: "devise_overrides/registrations"}

  resources :users, only: [:index] do
    resource :profile, :only => [:edit, :update, :show]
    resource :meetup_prompt, :only => [:destroy], :controller => 'users/meetup_prompts'
  end
  resources :meetup_users, :only => [:show]

  resources :locations

  resources :events do
    resources :organizers, :only => [:index, :create, :destroy]
    resources :checkiners, :only => [:index, :create, :destroy]
    resources :volunteers, :only => [:index, :update]

    resources :students, :only => [:index], :controller => 'events/students'
    resources :attendees, :only => [:index, :update], :controller => 'events/attendees'
    resources :emails, :only => [:new, :create], :controller => 'events/emails'

    resources :sections, :only => [:create, :update, :destroy] do
      post :arrange, on: :collection
    end

    resources :rsvps, :except => [:index, :new] do
      new do
        get :volunteer
        get :learn
      end
    end

    resources :event_sessions, :only => [:index] do
      resources :checkins, :only => [:index, :create, :destroy]
    end

    member do
      get "organize"
      get "organize_sections"
      get "levels"
      get "diets"
    end
  end

  resources :external_events

  get "/past_events" => "events#past_events"

  get "/about" => "static_pages#about"

  get "/auth/:provider/callback" => "omniauths#callback"

  if Rails.env.development?
    get "/style_guide" => "static_pages#style_guide"
  end
end

app/controllers/events/attendees_controller.rb
class Events::AttendeesController < ApplicationController
  before_filter :authenticate_user!, :validate_organizer!, :find_event

  def index
    @rsvps = @event.attendee_rsvps
  end

  def update
    @rsvp = @event.rsvps.find(params[:id])
    @rsvp.section_id = params[:attendee][:section_id]
    if @rsvp.save
      render json: @rsvp
    else
      render json: @rsvp, status: :unprocessable_entity
    end
  end

  def find_event
    @event = Event.find_by_id(params[:event_id])
  end
end

app/controllers/events/emails_controller.rb
class Events::EmailsController < ApplicationController
  before_filter :authenticate_user!, :validate_organizer!, :find_event

  def new
    @email = @event.event_emails.build(
      attendee_group: 'All',
    )
    assign_ivars
  end

  def create
    email_params = params[:event_email]

    if email_params[:attendee_group] == 'All'
      recipient_rsvps = @event.rsvps.where(role_id: [Role::VOLUNTEER.id, Role::STUDENT.id]).includes(:user)
    else
      recipient_rsvps = @event.rsvps.where(role_id: email_params[:attendee_group]).includes(:user)
    end

    unless email_params[:include_waitlisted]
      recipient_rsvps = recipient_rsvps.where(waitlist_position: nil)
    end

    @email = @event.event_emails.build(
      subject: email_params[:subject],
      body: email_params[:body],
      sender: current_user,
      recipient_rsvp_ids: recipient_rsvps.map(&:id),
      attendee_group: email_params[:attendee_group].to_i,
      include_waitlisted: email_params[:include_waitlisted]
    )

    unless @email.valid?
      assign_ivars
      return render :new
    end

    EventMailer.from_organizer(
      sender: current_user,
      recipients: recipient_rsvps.map { |rsvp| rsvp.user.email },
      subject: email_params[:subject],
      body: email_params[:body],
      event: @event
    ).deliver

    @email.save!

    redirect_to organize_event_path(@event), notice: "Your mail has been sent. Woo!"
  end

  private

  def find_event
    @event = Event.find_by_id(params[:event_id])
  end

  def assign_ivars
    @rsvps = @event.rsvps.where(role_id: [Role::VOLUNTEER.id, Role::STUDENT.id]).includes(:user)
    @emails = @event.event_emails.order(:created_at)

    @email_recipients = {}
    @emails.each do |email|
      @email_recipients[email.id] = {
        total: email.recipient_rsvps.length,
        volunteers: 0,
        students: 0
      }
      email.recipient_rsvps.each do |rsvp|
        if rsvp.role == Role::VOLUNTEER
          @email_recipients[email.id][:volunteers] += 1
        end
        if rsvp.role == Role::STUDENT
          @email_recipients[email.id][:students] += 1
        end
      end
    end
  end
end

app/controllers/events/students_controller.rb
require 'csv'

module Events
  class StudentsController < ApplicationController
    before_filter :authenticate_user!, :validate_organizer!
    respond_to :csv, :html

    def index
      @event = Event.find(params[:event_id])
      @students = @event.student_rsvps
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :past_events, :show, :levels]
  before_filter :find_event, except: [:index, :past_events, :create, :new]
  before_filter :validate_organizer!, except: [:index, :past_events, :create, :show, :new, :levels]
  before_filter :set_time_zone, only: [:create, :update]

  def index
    @events = Event.upcoming.includes(:event_sessions, :location)
    respond_to do |format|
      format.html do
        @past_events = sorted_past_events
      end
      format.json { render json: @events }
    end
  end

  def past_events
    respond_to do |format|
      format.json { render json: sorted_past_events }
    end
  end

  def show
    if user_signed_in? && !@event.historical?
      @organizer = @event.organizer?(current_user) || current_user.admin?
      @checkiner = @event.checkiner?(current_user)
    else
      @organizer = false
      @checkiner = false
    end
  end

  def new
    @event = Event.new(public_email: current_user.email, time_zone: current_user.time_zone)
    @event.event_sessions << EventSession.new
  end

  def edit
  end

  def create
    @event = Event.new(params[:event])

    if @event.save
      @event.organizers << current_user
      redirect_to @event, notice: 'Event was successfully created.'
    else
      render action: "new"
    end
  end

  def update
    if @event.update_attributes(params[:event])
      redirect_to @event, notice: 'Event was successfully updated.'
    else
      render status: :unprocessable_entity, action: "edit"
    end
  end

  def destroy
    @event.destroy
    redirect_to events_url
  end

  def organize
    @volunteer_rsvps = @event.volunteer_rsvps
    @volunteer_preference_counts = VolunteerPreference.all.inject({}) do |hsh, pref|
      hsh[pref.id] = 0
      hsh
    end
    @volunteer_assignment_counts = VolunteerAssignment.all.inject({}) do |hsh, assn|
      hsh[assn.id] = 0
      hsh
    end
    @volunteer_rsvps.each do |rsvp|
      @volunteer_assignment_counts[rsvp.volunteer_assignment_id] += 1
      @volunteer_preference_counts[rsvp.volunteer_preference_id] += 1
    end

    @childcare_requests = @event.rsvps_with_childcare

    @checkin_counts = @event.checkin_counts
  end

  def organize_sections
    respond_to do |format|
      format.html { render :organize_sections }
      format.json do
        render json: {
          sections: @event.sections,
          attendees: @event.rsvps_with_workshop_checkins
        }
      end
    end
  end

  def diets
  end

  protected

  def set_time_zone
    if params[:event] && params[:event][:time_zone].present?
      Time.zone = params[:event][:time_zone]
    end
  end

  def find_event
    @event = Event.find(params[:id])
  end

  def sorted_past_events
    past_bridgetroll_events = Event.past.includes(:location)
    past_external_events = ExternalEvent.all
    (past_bridgetroll_events + past_external_events).sort_by { |e| e.starts_at.to_time }
  end
end

app/helpers/events_helper.rb
module EventsHelper
  def get_volunteer_skills(volunteer_rsvp)
    profile = volunteer_rsvp.user.profile
    @skills = []
    @skills << 'Teaching'     if(volunteer_rsvp.teaching)
    @skills << 'TA-ing'       if(volunteer_rsvp.taing)
    @skills << 'Childcare'    if(profile.childcaring)
    @skills << 'Writing'      if(profile.writing)
    @skills << 'Outreach'      if(profile.outreach)
    @skills << 'Designing'    if(profile.designing)
    @skills << 'Mentoring'    if(profile.mentoring)
    @skills << 'Mac OS X'     if(profile.macosx)
    @skills << 'Windows'      if(profile.windows)
    @skills << 'Linux'        if(profile.linux)
    @skills.join(', ')
  end

  def rsvp_class(rsvp)
    if rsvp.waitlisted?
      return 'waitlisted'
    end
    if rsvp.no_show?
      return 'no-show'
    end
    return ''
  end

  def organizer_list
    @event.organizers_with_legacy.empty? ? [] : @event.organizers_with_legacy
  end

  def formatted_event_date(event)
    l event.date_in_time_zone(:starts_at), :format => :date_as_day_mdy
  end

  def formatted_session_date(event_session)
    l event_session.date_in_time_zone(:starts_at), :format => :date_as_day_mdy
  end

  def formatted_session_time(event_session, start_or_end)
    l event_session.date_in_time_zone(start_or_end), :format => :time_as_hm_ampm
  end

  def formatted_session_fancy_date(event_session)
    fancy_date = l event_session.date_in_time_zone(:starts_at), :format => :date_as_day_month_day_year
    "#{fancy_date}: #{event_session.name}"
  end

  def formatted_session_timerange(event_session)
    start_time = l event_session.date_in_time_zone(:starts_at), :format => :time_as_hm_ampm_no_zone
    end_time = l event_session.date_in_time_zone(:ends_at), :format => :time_as_hm_ampm_no_zone
    zone = l event_session.date_in_time_zone(:starts_at), :format => :time_zone
    "#{start_time} - #{end_time} #{zone}"
  end

  def formatted_session_datetime(event_session)
    "#{formatted_session_date(event_session)} - #{formatted_session_timerange(event_session)}"
  end

  def simple_format_with_html(string)
    simple_format(
      Sanitize.clean(string, Sanitize::Config::RELAXED),
      :sanitize => false
    )
  end

  def formatted_event_date_range(event)
    first_date = event.event_sessions.map { |s| s.date_in_time_zone(:starts_at) }.min
    last_date = event.event_sessions.map { |s| s.date_in_time_zone(:ends_at) }.max

    if first_date.year == last_date.year
      if first_date.month == last_date.month
        t :range_as_month_dayrange_year,
          :month => l(first_date, format: :date_as_m),
          first_day: first_date.day,
          last_day: last_date.day,
          year: first_date.year
      else
        t :range_as_monthrange_year,
          :first_month_day => l(first_date, format: :date_as_m_d),
          :last_month_day => l(last_date, format: :date_as_m_d),
          :year => first_date.year
      end
    else
      t :range_as_yearrange,
        :first_date => l(first_date, format: :date_as_m_d_y),
        :last_date => l(last_date, format: :date_as_m_d_y)
    end
  end

  def pretty_print_session(session)
    p = ''

    p << session.name
    p << " on #{formatted_session_date(session)}"
    p << " from #{formatted_session_timerange(session)}"
  end

  def verb(role)
    role == Role::STUDENT ? "attending" : "volunteering at"
  end

  def attend_button_text(event)
    event.at_limit? ? 'Join the waitlist' : 'Attend as a student'
  end
end

app/views/events/_form.html.erb
<div class="row-fluid">
  <div class="span6">
    <%= nested_form_for @event do |f| %>
      <% if @event.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

          <ul>
          <% @event.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field">
        <%= f.label :title %>
        <%= f.text_field :title %>
      </div>
      <div class="field">
        <%= f.label :course_id %>
        <%= collection_select :event, :course_id, Course.all, :id, :title %>
      </div>

      <h3>Sessions</h3>

      <em>There should be one session for each thing that a student or volunteer might be checked in for. This usually means 'Installfest' and 'Workshop'. If there's no Installfest, just keep the one session.</em>

      <div class="event-sessions">
        <%= f.fields_for :event_sessions do |event_sessions_form| %>
          <%= event_sessions_form.label :name, 'Session Name' %>
          <% if @event.new_record? %>
            <span class="remove-session hidden pull-right">(<a href="#">Remove Session</a>)</span>
          <% end %>
          <div><%= event_sessions_form.text_field :name %></div>

          <%= event_sessions_form.text_field :session_date, class: 'datepicker' %>
          <%= event_sessions_form.time_select :starts_at, {:ampm => true, :minute_step => 15}, {:class => "input-small start_time"} %>
          -
          <%= event_sessions_form.time_select :ends_at, {:ampm => true, :minute_step => 15}, {:class => "input-small end_time"} %>
        <% end %>
        <%= f.link_to_add :event_sessions do %>
          <span>Add a session</span>
        <% end %>
      </div>

      <div class="field">
        <%= f.label :time_zone %>
        <%= f.time_zone_select :time_zone, ActiveSupport::TimeZone.us_zones, include_blank: 'Select Time Zone' %>
      </div>

      <div class="field">
        <%= f.label :location_id %>
        <%= collection_select(:event, :location_id, Location.all, :id, :name, :prompt => true) %>
      </div>

      <div class="field">
        <%= f.label :allow_student_rsvp do %>
          <%= f.check_box :allow_student_rsvp %> Allow Student RSVP?
        <% end %>
      </div>

      <h3>Capacity</h3>

      <p>
        This sets be the maximum number of <strong>students</strong> you think could fit in your event.
        There is not a limit on the number of volunteer RSVPs, so you should consider
        the number of expected volunteers when determining student capacity. Most workshops
        have less than one volunteer for every student.
      </p>
      <p>
        <strong>
          After publishing, you can increase this, but not decrease it. Choose wisely!
        </strong>
      </p>

      <div class="field">
        <%= f.label :student_rsvp_limit, 'Student RSVP limit' %>
        <%= f.text_field :student_rsvp_limit %>
      </div>

      <div class="field">
        <%= f.label :public_email, 'What email address should users contact you at with questions?' %>
        <%= f.text_field :public_email, :class => "input-xxlarge"%>
      </div>

      <div class="field">
        <%= f.label :details, 'General Event Details (some html allowed)' %>
        <%= f.text_area :details, :rows => 14, :class => "input-xxlarge"%>
      </div>

      <div class="field">
        <%= f.label :volunteer_details, 'Volunteer Details' %>
        <%= f.text_area :volunteer_details, :rows => 4, :class => "input-xxlarge"%>
      </div>

      <% if @event.new_record? %>
        <h2>Ready to create your Event? Hold on a second...</h2>

        <p>Make sure you've read over the <a href="https://github.com/railsbridge/docs/wiki/Cookbook">Organizer's Cookbook</a> so you know what you're getting into.</p>

        <p>Pay particular attention to the <a href="https://github.com/railsbridge/docs/wiki/Workshop-Planning-Tasks">Workshop Planning Tasks</a> page. You're already posting an event on Bridge Troll, which is a thing on that page!</a></p>

        <p><b>If you post the event on Meetup</b>, please make only ONE event <i>(RailsBridge workshop at YOUR_VENUE)</i> and set the RSVP limit to 1 <i>(yourself)</i>. This event should be for publicity only (people who are a member of the Meetup group will get emailed about it) &mdash; you should direct attendees to do their actual registration on this Bridge Troll event.</p>
      <% end %>

      <div class="actions">
        <%= f.submit class: 'btn btn-submit' %>
      </div>
    <% end %>
  </div>
</div>

app/views/events/_upcoming_event.html.erb
<div class='upcoming-event'>
  <div class='event-title'>
    <%= link_to event.title, event %>
    <% if event.meetup_student_event_id %>
      <%= link_to "[S]", event.meetup_url(event.meetup_student_event_id), class: 'meetup-link' %>
    <% end %>
    <% if event.meetup_volunteer_event_id %>
      <%= link_to "[V]", event.meetup_url(event.meetup_volunteer_event_id), class: 'meetup-link' %>
    <% end %>
  </div>
  <div class='event-times'>
    <% event.event_sessions.each_with_index do |session, index| %>
      <i class='icon-calendar'></i><%= formatted_session_fancy_date(session) %><% if index < event.event_sessions.length - 1 %><br /><% end %>
    <% end %>
  </div>
  <div class='event-location'>
    <% if event.location %>
      <i class='icon-map-marker'></i><%= event.location.name %>,
      <%= "#{event.location.city}, #{event.location.state}" %>
    <% end %>
  </div>
  <div class='event-counts'>
    <div><i class='icon-user'></i>Volunteers: <%= event.volunteer_rsvps.count %></div>
    <div>
      <i class='icon-user'></i>Students: <%= event.student_rsvps.count %> / <%= event.student_rsvp_limit %>
      <% if event.at_limit? %>
        (<%= event.student_waitlist_rsvps.count %> Waitlisted)
      <% end %>
    </div>
  </div>
  <div class='event-actions'>
    <% if user_signed_in? %>
      <%= render 'shared/rsvp_actions', event: event %>
      <% if event.organizer?(current_user) || current_user.admin? %>
        <%= link_to 'Organizer Console', organize_event_path(event), :class => 'btn' %>
      <% elsif event.checkiner?(current_user) %>
        <%= link_to 'Checkin Console', event_event_sessions_path(event), :class => 'btn' %>
      <% end %>
    <% else %>
      <%= render 'shared/rsvp_actions_unauthenticated', event: event, stay_on_event: true %>
    <% end %>
  </div>
</div>

app/views/events/diets.html.erb
<%= content_for(:header_text, @event.title) %>
<%= content_for(:header_link, organize_event_path(@event)) %>

<%= render :partial => 'shared/organizer_breadcrumb', locals: {current_page_title: 'Food Preferences'} %>
<div class='food-preferences'>
  <h2>Total Attendees: <%= @event.rsvps.count %></h2>

  <h2>Dietary Restrictions Totals</h2>
  <% totals = @event.dietary_restrictions_totals %>
  <% DietaryRestriction::DIETS.each do |diet| %>
    <h3><%= "#{diet.capitalize}: #{totals[diet] || 0}" %></h3>
  <% end %>

  <h2>Other dietary restrictions:</h2>
  <ul>
  <% @event.other_dietary_restrictions.each do |other| %>
    <li><%= other %></li>
  <% end %> 
  </ul>
</div>

app/views/events/edit.html.erb
<%= content_for(:header_text, @event.title) %>
<%= content_for(:header_link, event_path(@event)) %>

<h1>Editing event</h1>

<%= render 'form' %>

<%= render 'shared/actions', links: [
  ['Back', @event],
  ['Manage Locations', locations_path],
] %>

app/views/events/index.html.erb
<% unless user_signed_in? %>
  <%= render 'shared/welcome' %>
<% end %>

<div class="row-fluid">
  <div class="span12">
    <div class='upcoming-events'>
      <h1>Upcoming events</h1>

      <% if @events.empty? %>
        <h2>There are currently no upcoming events.</h2>
      <% end %>
      <% @events.each do |event| %>
        <%= render 'upcoming_event', event: event %>
      <% end %>
    </div>

    <div class='past-events'>
      <h1>Past events</h1>
      <table class="<%= @past_events.any? ? 'datatable-sorted' : '' %> table table-striped table-bordered table-condensed">
        <thead>
        <tr>
          <th>Title</th>
          <th class='date'>Date</th>
          <th>Venue</th>
          <th>City</th>
        </tr>
        </thead>

        <tbody>
        <% if @past_events.empty? %>
          <tr>
            <td colspan="5">There are no past events.</td>
          </tr>
        <% end %>
        <% @past_events.each do |event| %>
          <tr>
            <td>
              <%= link_to event.title, event.respond_to?(:url) ? event.url : event %>
              <% if event.meetup_student_event_id %>
                <%= link_to "[S]", event.meetup_url(event.meetup_student_event_id), class: 'meetup-link' %>
              <% end %>
              <% if event.meetup_volunteer_event_id %>
                <%= link_to "[V]", event.meetup_url(event.meetup_volunteer_event_id), class: 'meetup-link' %>
              <% end %>
            </td>
            <td>
              <%= formatted_event_date(event) %>
            </td>
            <% if event.location %>
              <td><%= event.location_name %></td>
              <td><%= event.location_city_and_state %></td>
            <% else %>
              <td></td>
              <td></td>
            <% end %>
          </tr>
        <% end %>
        </tbody>
      </table>

      <% if user_signed_in? %>
        <% links = [
          ['Organize Event', new_event_path],
          ['Manage Locations', locations_path]
        ] %>
        <% if current_user.admin? %>
          <% links << ['Manage External Events', external_events_path] %>
        <% end %>
        <%= render 'shared/actions', links: links %>
      <% end %>
    </div>
  </div>
</div>

app/views/events/levels.html.erb
<%= content_for(:header_text, @event.title) %>
<%= content_for(:header_link, event_path(@event)) %>

<h2>Class Levels for <%= (@event.course || Course::RAILS).title %></h2>

<div id="level_buttons">
  <% (@event.course || Course::RAILS).levels.each do |level| %>
    <div class="class_level_line">
      <label class='class_level'>
        <span class="<%= "label btn-#{level[:color]}" %>"><%= level[:color].capitalize %></span>
        <%= level[:title] %>
      </label>
      <ul>
      <% level[:popover_content].each do |desc| %>
        <li><%= desc %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
</div>

app/views/events/new.html.erb
<%= content_for(:header_text, 'Organize an Event') %>

<%= render 'form' %>

<%= render 'shared/actions', links: [
  ['Back', events_path],
  ['Manage Locations', locations_path]
] %>

app/views/events/organize.html.erb
<%= content_for(:header_text, @event.title) %>
<%= content_for(:header_link, event_path(@event)) %>

<%= render :partial => 'shared/organizer_breadcrumb', locals: {current_page_title: 'Organizer Console'} %>

<% [
     [new_event_email_path(@event), 'icon-envelope', 'Email Attendees'],
     [event_attendees_path(@event), 'icon-info-sign', 'Show all Attendee Details'],
     [event_organizers_path(@event), 'icon-key', 'Manage Organizers'],
     [diets_event_path(@event), 'icon-food', 'Dietary Needs']
   ].each do |button| %>
<%= render partial: 'shared/organizer_action', locals: {
    path: button[0],
    icon: button[1],
    text: button[2]
  } %>
<% end %>

<section class='organizer-dashboard-section'>
  <%= link_to organize_sections_event_path(@event) do %>
    <div class='section-arranger-link'>
      <img src='/assets/section_organizer_small.png'><span class='section-arranger-link-text'>Arrange Sections</span>
    </div>
  <% end %>
</section>

<section class='organizer-dashboard-section'>
  <%= render :partial => 'shared/checkin_event_sessions' %>
  <%= render partial: 'shared/organizer_action', locals: {
    path: event_checkiners_path(@event),
    icon: 'icon-check',
    text: 'Add Checkiners'
  } %>
</section>

<section class='organizer-dashboard-section'>
  <h2>Childcare Requests</h2>
  <table class="table">
    <thead>
    <tr>
      <th>Requester Name</th>
      <th>Email</th>
      <th>Children Info</th>
    </tr>
    </thead>
    <tbody>
    <% @childcare_requests.each do |request| %>
      <tr>
        <td>
          <%= request.user.full_name %>
        </td>
        <td>
          <%= request.user.email %>
        </td>
        <td>
          <%= request.childcare_info %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
</section>

app/views/events/organize_sections.html.erb
<%= content_for(:header_text, @event.title) %>
<%= content_for(:header_link, organize_event_path(@event)) %>

<%= render :partial => 'shared/organizer_breadcrumb', locals: {current_page_title: 'Section Organizer'} %>

<div id="section-organizer" class="showing-unassigned"></div>

<script>
  $(document).ready(function () {
    var attendees = new Bridgetroll.Collections.Attendee(
      <%= @event.rsvps_with_workshop_checkins.to_json.html_safe %>
    );
    var sections = new Bridgetroll.Collections.Section(
      <%= @event.sections.to_json.html_safe %>
    );

    Bridgetroll.sectionOrganizer = new Bridgetroll.Views.SectionOrganizer({
      event_id: <%= @event.id %>,
      sections: sections,
      attendees: attendees
    });
    Bridgetroll.sectionOrganizer.setElement($('#section-organizer'));
    Bridgetroll.sectionOrganizer.render();
  });
</script>

app/views/events/show.html.erb
<%= content_for(:header_text, @event.title) %>

<div class="row-fluid">
  <div class="span8">
    <div class="critical-details">
      <% if @event.location %>
        <%= link_to pretty_print_address(@event.location), location_map_link(@event.location) %>
      <% else %>
        This event currently has no location!
      <% end %>
    </div>

    <div class='session-display'>
      <% @event.event_sessions.each do |event_session| %>
        <div class='event-session'>
          <h2 class='name'><%= event_session.name %></h2>

          <div class='date'><%= formatted_session_date(event_session) %></div>
          <div class='time'>Start time: <%= formatted_session_time(event_session, :starts_at) %></div>
          <div class='time'>End time: <%= formatted_session_time(event_session, :ends_at) %></div>
        </div>
      <% end %>
    </div>
    <% unless @event.course == nil %>
      <div id="course">
        <h2>Course</h2>
          <p>
            <%= @event.course.description.html_safe %>
            <%= link_to "Click here for more information about class levels in this course!", levels_event_path(@event) %>
          </p>
      </div>
    <% end %>
    <div class="details">
      <%= simple_format_with_html(@event.details) %>
    </div>

    <% links = [] %>

    <% if @organizer %>
      <% links << ['Edit', edit_event_path(@event)] %>
      <% links << ['Organizer Console', organize_event_path(@event)] %>
    <% elsif @checkiner %>
      <% links << ['Checkin Console', event_event_sessions_path(@event)] %>
    <% end %>

    <% links << ['Back', events_path] %>

    <%= render 'shared/actions', links: links %>

  </div>
  <div class="span4">

    <div class='location-display'>
      <% if @event.location.present? %>
        <%= render "shared/map", location: @event.location %>
      <% end %>
    </div>

    <% unless @event.historical? %>
      <div class='rsvp-actions'>
        <% if user_signed_in? %>
          <%= render 'shared/rsvp_actions', event: @event %>
        <% else %>
          <%= render 'shared/rsvp_actions_unauthenticated', event: @event, stay_on_event: false %>
        <% end %>
      </div>
    <% end %>

    <div class="organizers">
      <h3>Organized By:</h3>
      <ul>
        <% if organizer_list.any? %>
          <% organizer_list.each do |organizer| %>
            <li><%= organizer.full_name %></li>
          <% end %>
        <% else %>
          <li>No Organizer Assigned</li>
        <% end %>
      </ul>
      <% if user_signed_in? && @event.public_email.present? %>
        <p>Questions? Email
          <%= mail_to @event.public_email %>
        </p>
      <% end %>
    </div>
    <h3><%= pluralize(@event.checked_in_volunteer_rsvps.count, "volunteer") %>!</h3>
    <% if @event.volunteer_rsvps.none? %>
      No volunteers are currently signed up for this event.
    <% else %>
      <ul class="attendees">
        <% @event.ordered_volunteer_rsvps.each do |rsvp| %>
          <li class='attendee'><%= render 'shared/viewed_gravatars', :email => rsvp.user.email %><%= link_to rsvp.user.full_name, rsvp.user.profile_path, class: rsvp_class(rsvp) %></li>
        <% end %>
      </ul>
    <% end %>
    <h3><%= pluralize(@event.checked_in_student_rsvps.count, "student") %>!</h3>
    <% if @event.student_rsvps.none? %>
      No students are currently signed up for this event.
    <% else %>
      <ul class="attendees">
        <% @event.ordered_student_rsvps.each do |rsvp| %>
          <li class='attendee'><%= render 'shared/viewed_gravatars', :email => rsvp.user.email %><%= link_to rsvp.user.full_name, rsvp.user.profile_path, class: rsvp_class(rsvp) %></li>
        <% end %>
      </ul>
    <% end %>

    <% if @event.student_waitlist_rsvps.any? %>
      <h3>Waitlist</h3>
      <ul class="attendees">
        <% @event.student_waitlist_rsvps.each do |rsvp| %>
          <li class='attendee'><%= render 'shared/viewed_gravatars', :email => rsvp.user.email %><%= link_to rsvp.user.full_name, rsvp.user.profile_path, class: rsvp_class(rsvp) %></li>
        <% end %>
      </ul>
    <% end %>
  </div>
</div>